import Head from "next/head";
import React from "react";
import PostByCommentId from "src/components/Post/PostByCommentId";
import { useComment } from "src/hooks/useComment";

export const Comment = () => {
  const { data, error, isLoading } = useComment();

  if (isLoading) {
    return <div>ローディング中です</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="text-3xl font-bold">{data.body}</h1>
      <div>Created by {data.name}</div>
      <h2 className="text-xl font-bold mt-10">元の記事</h2>
      <PostByCommentId id={data.postId} />
    </div>
  );
};
