import React from "react";
import Head from "next/head";
import { Header } from "src/components/Header";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <h1>Next.js</h1>
      <p>JSONPlaceholder</p>
    </div>
  );
};

export default Index;
