import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { CommentsByPostId } from "src/components/Comments/CommentsByPostId";
import { UserByUserId } from "src/components/User/UserByUserId";
import { fetcher } from "src/utils/fetcher";
import useSWR from "swr";

export const Post = () => {
  const router = useRouter();
  const { data, error } = useSWR(
    router.query.id ? `https://jsonplaceholder.typicode.com/posts/6` : null,
    fetcher
  );

  if (!data && !error) {
    return <div>ローディング中です</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{data?.title}</h1>
      <p>{data?.body}</p>
      <UserByUserId id={data?.id} />
      <CommentsByPostId id={data?.id} />
    </div>
  );
};
