import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { CommentsByPostId } from "src/components/Comments/CommentsByPostId";
import { UserByUserId } from "src/components/User/UserByUserId";
import { usePost } from "src/hooks/usePost";

export const Post = () => {
  const router = useRouter();
  const { post, error, isLoading } = usePost(router.query.id);

  if (isLoading) {
    return <div>ローディング中です</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <div>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{post?.title}</h1>
      <p>{post?.body}</p>
      <UserByUserId id={post?.id} />
      <CommentsByPostId id={post?.id} />
    </div>
  );
};
